### PR TITLE
File view fixes

### LINKED ISSUE #119: Sorting: Files: List ist not sorted by filename
If I browse files via "Files" the list is not sorted by filename instead by "display name".

In case of music, if I have e.g. two files "01 Zong.mp3" and "02 Song.mp3" the second one displays first, because its ID3-Tag says "Song".

The same happens with files of episodes of tv series.

It would be nice to have the option to sort these lists by filename. :)

thx

### PR DESCRIPTION
**Pull request by sebastian-de**
Sort file lists by path and show filename in details
These patches fix #119 and #65
Screenshots: https://github.com/xbmc/Kore/issues/65#issuecomment-296399554

It also contains a fix for http://forum.kodi.tv/showthread.php?tid=278792

### CODE REVIEW

**Comment by SyncedSynapse** [comment]
Thanks for this. I have some comments on it tough, so i would appreciate if you could review them.

File: app/src/main/java/org/xbmc/kore/ui/sections/file/MediaFileListFragment.java [hunk 1]
```diff
@@ -323,7 +324,7 @@ private void browseDirectory(final FileLocation dir) {
 
         Files.GetDirectory action = new Files.GetDirectory(dir.file,
                 mediaType,
-                new ListType.Sort(ListType.Sort.SORT_METHOD_LABEL, true, true),
+                new ListType.Sort(ListType.Sort.SORT_METHOD_PATH, true, true),
```
Comment (SyncedSynapse) [inline app/src/main/java/org/xbmc/kore/ui/sections/file/MediaFileListFragment.java]: Ideally this would be an option on the overflow menu, like it is for instance in the movies section. Nvertheless, if you're not confortable implementing it, leave it and i'll merge it as is.

File: app/src/main/java/org/xbmc/kore/ui/sections/file/MediaFileListFragment.java [hunk 2]
```diff
@@ -511,16 +512,15 @@ public boolean onMenuItemClick(MenuItem item) {
                                     case R.id.action_play_from_this_item:
                                         mediaQueueFileLocation.clear();
                                         FileLocation fl;
+                                        // start playing the selected one, then queue the rest
+                                        mediaQueueFileLocation.add(loc);
+                                        playMediaFile(loc.file);
```
Comment (SyncedSynapse) [inline app/src/main/java/org/xbmc/kore/ui/sections/file/MediaFileListFragment.java]: Slight possible bug here. `PlayMediaFile` needs to be the last thing on this block, as it also sends the queued items to Kodi, so `mediaQueueFileLocation` needs to be full before calling it.
Actually i don't think that `PlayMediaFile` should do this, but it's how it's implemented right now, so to avoid a possible bug this needs to be left as the last line before the return.

File: app/src/main/java/org/xbmc/kore/ui/sections/file/MediaFileListFragment.java [hunk 3]
```diff
@@ -717,9 +717,17 @@ public static FileLocation newInstanceFromItemFile(Context context, ListType.Ite
                     artUrl = itemFile.thumbnail;
                     break;
                 case ListType.ItemBase.TYPE_ALBUM:
+                    title = itemFile.displayartist + " | " + itemFile.album;
+                    details = new File(itemFile.file).getName();
```
Comment (SyncedSynapse) [inline app/src/main/java/org/xbmc/kore/ui/sections/file/MediaFileListFragment.java]: I don't particularly like that we are creating a `File` object for each item on the directory. I get that it is the easiest way to get the filename all parsed up, but it is kind of wasteful.
Furthermore there's a probable bug here: take a look at the `getName` implementation and you'll notice that it used a `fileSystemSeparator` to get the last part of the name. The thing is, this always returns Android's file system separator (ext4 `\`), not the one where Kodi resides, so if Kodi is on windows, the path probably contains `/` and this won't work. Haven't tested this tough, it's just an hypothesis.

File: app/src/main/java/org/xbmc/kore/ui/sections/file/MediaFileListFragment.java [hunk 4]
```diff
@@ -717,9 +717,17 @@ public static FileLocation newInstanceFromItemFile(Context context, ListType.Ite
...
+                    artUrl = itemFile.thumbnail;
+                    sizeDuration = (itemFile.size > 0) && (itemFile.duration > 0) ?
+                                   UIUtils.formatFileSize(itemFile.size) + " | " + UIUtils.formatTime(itemFile.duration) :
+                                   (itemFile.size > 0) ? UIUtils.formatFileSize(itemFile.size) :
+                                   (itemFile.duration > 0)? UIUtils.formatTime(itemFile.duration) : null;
+                    break;
                 case ListType.ItemBase.TYPE_SONG:
                     title = itemFile.label;
-                    details = itemFile.displayartist + " | " + itemFile.album;
+                    details = new File(itemFile.file).getName();
```
Comment (SyncedSynapse) [inline app/src/main/java/org/xbmc/kore/ui/sections/file/MediaFileListFragment.java]: Same as the last one

**Comment by sebastian-de** [comment]
Thank you very much for reviewing my PR, I'll rework some of the things according to your comments in the coming days.

**Comment by sebastian-de** [comment]
I only use Linux, so I can't check if getFilenameFromPath() works with Windows paths, but I copied most of it from getParentDirectory(), so this should work.

File: app/src/main/java/org/xbmc/kore/ui/sections/file/MediaFileListFragment.java (hunk 1 above)
Comment (sebastian-de) [inline app/src/main/java/org/xbmc/kore/ui/sections/file/MediaFileListFragment.java]: I will need some time to implement this, so it would be nice if you could merge this change as is. I'll try to look into this though - if I succeed I'll send another PR.
I'm still not completely happy with SORT_METHOD_PATH anyway, as some files don't seem to get sorted by path/filename, but I can't figure out why.

**Comment by bigretromike** [comment]
Will this fix problem with sorting episodes by episode number and not by episode title ? Is there a way to pick sort option like in webview ?

**Comment by sebastian-de** [comment]
All I can say is that addons will be affected, since the addon section uses MediaFileListFragment. How exactly will depend on the virtual file tree of your addon. You can find details on  how Kore handles addons here: https://github.com/xbmc/Kore/pull/239
It'll be best if you try current Kore master and see if your issue is fixed.
With my changes you'll see the filename of each item in its second row (in this case the virtual filename returned by your addon).
